
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int METHOD_CALL = 41;
  public static final int REF_TYPE = 48;
  public static final int MULT = 28;
  public static final int EQUALS = 25;
  public static final int LPAREN = 4;
  public static final int START_COMMENT = 50;
  public static final int INT = 18;
  public static final int PRINTLN = 23;
  public static final int NEW_INT_ARRAY = 40;
  public static final int MINUS = 27;
  public static final int R_CURLY_BRACKET = 7;
  public static final int STATIC = 8;
  public static final int RPAREN = 5;
  public static final int NOT = 37;
  public static final int SEMICOLON = 15;
  public static final int AND = 30;
  public static final int LT = 29;
  public static final int COMMA = 16;
  public static final int CLASS = 3;
  public static final int PLUS = 26;
  public static final int ASSIGN = 45;
  public static final int MAIN = 9;
  public static final int IF = 21;
  public static final int THIS = 34;
  public static final int DOT = 46;
  public static final int ID = 36;
  public static final int R_BRACKET = 13;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int RETURN = 17;
  public static final int ARRAY_ACCESS = 43;
  public static final int TRUE = 32;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int L_CURLY_BRACKET = 6;
  public static final int NUMBER = 19;
  public static final int ASSIGN_ARRAY = 44;
  public static final int VOID = 10;
  public static final int PARANTHESES = 38;
  public static final int ARRAY_LENGTH = 42;
  public static final int ELSE = 24;
  public static final int WHILE = 22;
  public static final int PUBLIC = 2;
  public static final int EXTENDS = 14;
  public static final int END_VARS = 47;
  public static final int STRING = 11;
  public static final int END_COMMENT = 49;
  public static final int FALSE = 33;
  public static final int L_BRACKET = 12;
  public static final int NEW_OBJECT = 39;
  public static final int LENGTH = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUBLIC",
  "CLASS",
  "LPAREN",
  "RPAREN",
  "L_CURLY_BRACKET",
  "R_CURLY_BRACKET",
  "STATIC",
  "MAIN",
  "VOID",
  "STRING",
  "L_BRACKET",
  "R_BRACKET",
  "EXTENDS",
  "SEMICOLON",
  "COMMA",
  "RETURN",
  "INT",
  "NUMBER",
  "BOOLEAN",
  "IF",
  "WHILE",
  "PRINTLN",
  "ELSE",
  "EQUALS",
  "PLUS",
  "MINUS",
  "MULT",
  "LT",
  "AND",
  "LENGTH",
  "TRUE",
  "FALSE",
  "THIS",
  "NEW",
  "ID",
  "NOT",
  "PARANTHESES",
  "NEW_OBJECT",
  "NEW_INT_ARRAY",
  "METHOD_CALL",
  "ARRAY_LENGTH",
  "ARRAY_ACCESS",
  "ASSIGN_ARRAY",
  "ASSIGN",
  "DOT",
  "END_VARS",
  "REF_TYPE",
  "END_COMMENT",
  "START_COMMENT"
  };
}

